// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/user": {
            "get": {
                "description": "Gets the basic user info by their id",
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "root"
                ],
                "summary": "gets user by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the user to retrieve",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "description": "Send new user struct to update user in db",
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "root"
                ],
                "summary": "updates user with incoming json struct",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/record/last": {
            "get": {
                "description": "Gets the last record from records for given user id and substance id, if no substance id provided, gets last record for all substances",
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "root"
                ],
                "summary": "gets last record for given user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the user to retrieve last record",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "value of the substance",
                        "name": "substance",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/substances/all": {
            "get": {
                "description": "Gets al substances that are by default accessible to user",
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "root"
                ],
                "summary": "gets all substances from db",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
