info:
  contact: {}
paths:
  /api/user:
    get:
      description: Gets the basic user info by their id
      parameters:
      - description: ID of the user to retrieve
        in: query
        name: userId
        required: true
        type: string
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: gets user by id
      tags:
      - user
    put:
      description: Send new user struct to update user in db
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: updates user with incoming json struct
      tags:
      - user
  /record/last:
    get:
      description: Gets the last record from records for given user id and substance
        id, if no substance id provided, gets last record for all substances
      parameters:
      - description: ID of the user to retrieve last record
        in: query
        name: userId
        required: true
        type: string
      - description: value of the substance
        in: query
        name: substance
        type: string
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: gets last record for given user
      tags:
      - record
  /substances/all:
    get:
      description: Gets al substances that are by default accessible to user
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: gets all substances from db
      tags:
      - substance
swagger: "2.0"
