name: Docker Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Build
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          builder: ${{ steps.build.outputs.name }}
          push: false
          tags: '${{ secrets.REGISTRY_URL }}/bahno_bot:latest'
          cache-from: 'type=registry,ref=${{ secrets.REGISTRY_URL }}bahno_bot:buildcache'
          cache-to: 'type=registry,ref=${{ secrets.REGISTRY_URL }}/bahno_bot:buildcache,mode=max'